apiVersion: apps/v1
kind: Deployment
metadata:
  name: something-api-deployment
  labels:
    app: something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: something-api
  template:
    metadata:
      labels:
        app: something-api
    spec:
      containers:
      - name: something-api
        image: djdols420/something-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: URLS 
          value: "http://*:80"