apiVersion: v1
kind: Service
metadata:
  name: api-service-https
  labels:
    app: something
spec:
  selector:
    app: something-api-https
  ports:
    - name: https-something-api
      protocol: TCP
      port: 443
      targetPort: 443