apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: something
spec:
  selector:
    app: something-api
  ports:
    - name: something-api
      protocol: TCP
      port: 80
      targetPort: 80