apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: jobs
profiles:
  - name: local
    build:
      tagPolicy:
        customTemplate:
          template: "dev"
      local:
        push: false
      artifacts:
        - image: djdols420/something-api
          context: .
          docker:
            dockerfile: src/Something.Api/Dockerfile
        - image: djdols420/counter-app
          context: .
          docker:
            dockerfile: src/Counter.Host/Dockerfile
    deploy:
      helm:
        releases:
        - name: something-dev
          chartPath: ./deploy
          valuesFiles:
          - ./deploy/values.yaml

