apiVersion: v1
kind: Service
metadata:
  name: api-service-http
  labels:
    app: something
spec:
  selector:
    app: something
  ports:
    - name: http-something-api
      protocol: TCP
      port: 80
      targetPort: 80